data_path: "data/final.csv"

missing_value_ratio: 0.7
# percential
lower_quantile: 0 
upper_quantile: 1

timesteps: 5
num_features: 7
batch_size: 8

prob_noise: 0

missing_value_min_size: 0
missing_value_max_size: 5 
prob_noise: 0.5
placeholder_value: -0.1

train_ratio: 0.8

learning_rate: 0.0000789

epochs: 1
num_epoch: 0